name: Node.js CI with Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build and Test
      run: npm run build --if-present && npm test

  coveralls:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Coverage to Coveralls
        run: |
          npm install -g nyc coveralls
          npx nyc report --reporter=text-lcov > coverage.lcov
          npx coveralls < coverage.lcov
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
