name: Node.js CI with Coveralls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests and generate coverage
        run: npm test

  coveralls:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install nyc and coveralls
        run: npm install nyc coveralls --no-save

      - name: Create .nyc_output directory
        run: mkdir -p .nyc_output

      - name: Print .nyc_output contents
        run: ls -a .nyc_output

      - name: Upload Coverage to Coveralls
        run: npx nyc report --reporter=text-lcov --report-dir=.nyc_output && npx coveralls < .nyc_output/lcov-report/lcov.info
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
