name: Node.js CI with Coveralls

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install nyc
        run: npm install -g nyc

      - name: Build project
        run: npm run build --if-present

      - name: Run tests and coverage
        run: npm test -- --coverage

  coveralls:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install nyc
        run: npm install -g nyc

      - name: Coveralls
        run: |
          npm run coverage
          npx coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
