name: Node.js CI with Coveralls

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Install nyc
        run: npm install nyc

      - name: Debug Coverage Directory
        run: ls -R ./coverage

      - name: Run tests and coverage
        run: |
          npm test -- --coverage
          nyc report --reporter=text-lcov --report-dir=./coverage/lcov-report
          
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
